#!/bin/bash

if [ $# -ne 1 ]
then
  echo 'Must supply destination project path!'
  exit 1
fi

DEST=${1%/}

NAME="${DEST#*/}"

files=(
  src/ spec/
  .gitignore .npmignore .travis.yml
  Gruntfile.js
  package.json
  README.md
)

echo "creating $DEST"
rm -rdf $DEST
mkdir -p $DEST

echo "copying folder to $DEST"
cp -r "${files[@]}" $DEST

echo "creating sublime project: $DEST/$NAME.sublime-project"
cp *.sublime-project $DEST/$NAME.sublime-project
cd $DEST
sed -i "s/livescript-stub/$NAME/g" *.json *.md

mv src/dummy.ls src/$NAME.ls
mv spec/dummy-spec.ls spec/$NAME-spec.ls
sed -i "s/dummy/$NAME/g" src/* spec/*

npm_modules=(
  prelude-ls
  grunt
  grunt-contrib-watch
  grunt-livescript
  grunt-contrib-clean
  grunt-lineending
  grunt-verbosity
  mocha
  grunt-mocha-test
  expect.js
)

echo "installing module"
npm update -g "${npm_modules[@]}"
npm ln "${npm_modules[@]}"
npm install

echo done
